[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rwa_program = "RWAaPWC9witz2n2vSA24KetECWPyCkBhSaBmr8MpXu9"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
